server:
  port: 8076



spring:
  redis:
    database: 2
    password: root
    host: 139.196.100.40
    port: 6379

#springboot文件上传文件大小限制配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
